site:
  title: Cockpit Docs
  start_page: cockpit-guide::index.adoc
  robots: allow
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
content:
  sources:
  - url: https://github.com/cockpit-project/cockpit.git
    # Disable branches
    branches:
      - main
    tags:
      # Catch all
      - "*"
      # Except for
      - "!3{0..5}*"
      - "!360"
      - "!{0..2}*"
      - "!v*"
    version: true
    start_path: doc/
runtime:
  fetch: true
  cache_dir: ./cache
  log:
    format: pretty
    level: fatal
ui:
  bundle:
    # TODO: Check if Fedora's Antora UI kit is better in some way
    # TODO: Add supplemental CSS and header to make it more Cockpit-like
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
antora:
  extensions:
  - id: cockpit-prerelease
    require: ./extensions/antora/cockpit-prerelease.js
    enabled: true

  - id: lunr
    require: '@antora/lunr-extension'
    index_latest_only: true
    enabled: true
asciidoc:
  extensions:
  - ./extensions/asciidoc/man-inline-replace.js
  - ./extensions/asciidoc/cockpit-inline-release.js
